### ISSUE TITLE
Analisis de la app de realidad aumentada

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/actividad-2-analisis-de-app-de-realidad-aumentada-dream-team1-0#1]
[Analisis-Quiver.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-analisis-de-app-de-realidad-aumentada-dream-team1-0/files/10843354/Analisis-Quiver.pdf)

**Comment by bg55-a** [comment]
Calificacion: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
